-- Create schemas
CREATE SCHEMA IF NOT EXISTS django;
CREATE SCHEMA IF NOT EXISTS roadmap;
CREATE SCHEMA IF NOT EXISTS users;
CREATE SCHEMA IF NOT EXISTS exam;
CREATE SCHEMA IF NOT EXISTS media;

-- Grant permissions
GRANT ALL PRIVILEGES ON SCHEMA django TO postgres;
GRANT ALL PRIVILEGES ON SCHEMA roadmap TO postgres;
GRANT ALL PRIVILEGES ON SCHEMA users TO postgres;
GRANT ALL PRIVILEGES ON SCHEMA exam TO postgres;
GRANT ALL PRIVILEGES ON SCHEMA media TO postgres;
