# Generated by Django 6.0 on 2026-01-08 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gaming_app', '0001_initial_gaming_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('isactive', models.BooleanField(db_column='isactive', default=True)),
            ],
            options={
                'db_table': 'badge',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('order', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('requiredpoints', models.IntegerField()),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('isactive', models.BooleanField(db_column='isactive', default=True)),
            ],
            options={
                'db_table': 'level',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('actiontype', models.CharField(db_column='actiontype', max_length=100)),
                ('pointsearned', models.IntegerField(db_column='pointsearned', default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('createdat', models.DateTimeField(auto_now_add=True, db_column='createdat')),
            ],
            options={
                'db_table': 'useraction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('earnedat', models.DateTimeField(db_column='earnedat')),
            ],
            options={
                'db_table': 'userbadge',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('currentpoints', models.IntegerField(db_column='currentpoints', default=0)),
                ('reachedat', models.DateTimeField(db_column='reachedat')),
            ],
            options={
                'db_table': 'userlevel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserPoint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('totalpoints', models.IntegerField(db_column='totalpoints', default=0)),
                ('lastupdated', models.DateTimeField(blank=True, db_column='lastupdated', null=True)),
            ],
            options={
                'db_table': 'userpoint',
                'managed': False,
            },
        ),
    ]
