"""
Django settings for kebrit_api project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import environ

# Initialize environment variables
env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Take environment variables from .env file
# Try .env first, fallback to .env.example if .env doesn't exist
env_file = BASE_DIR / '.env.example'
environ.Env.read_env(env_file)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-7lht3a&6zlzd%(%yv^8w2=zqp((z0cv_@piw&dg=s-%ifkex7x')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG', default=True)

ALLOWED_HOSTS = ['testserver','localhost','127.0.0.1','htni.ir','app.htni.ir','ayareto.ir','ayareto.com','app.ayareto.com','app.ayareto.ir','api.ayareto.ir','api.ayareto.com']

import sentry_sdk

sentry_sdk.init(
    dsn="https://860721a2ee404e13dcbdd68e61cba563@sentry.hamravesh.com/9657",
    # Add data like request headers and IP for users,
    # see https://docs.sentry.io/platforms/python/data-management/data-collected/ for more info
    send_default_pii=True,
)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third party apps
    'rest_framework',
    'corsheaders',
    'drf_yasg',  # Swagger/OpenAPI documentation
    # Local apps
    'kebrit_api',  # ADD THIS: For migrations
    'users_app',
    'roadmap_app',
    'exam_app',
    'media_app.apps.MediaAppConfig',
    'gaming_app.apps.GamingAppConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # CSRF enabled for admin panel, but exempted for API endpoints via @csrf_exempt
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'kebrit_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kebrit_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD',),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT'),
        'OPTIONS': {
            # Django tables will be created in 'django' schema
            # Application tables use their own schemas (roadmap, users, exam, media, gaming)
            'options': '-c search_path=django,roadmap,users,exam,media,gaming,public'
        },
    }
}

# Database router (optional, for more control)
DATABASE_ROUTERS = ['kebrit_api.db_router.DjangoSchemaRouter']


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_TZ = True

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # احراز هویت پیش‌فرض فقط با Client Token از هدر X-Client-Token
        'kebrit_api.authentication_client.ClientTokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100,
}

# Exam frontend base URL used for returning exam_url in integration launch endpoint.
# Example: https://app.ayareto.ir/exam
EXAM_FRONT_BASE_URL = env('EXAM_FRONT_BASE_URL', default='')

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:8000",
    "https://k.htni.ir",
    "https://app.ayareto.ir",
    "https://app.ayareto.com",
    "https://htni.ir",
]

CORS_ALLOW_CREDENTIALS = True

# CORS additional settings for preflight requests
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-client-token',  # برای احراز هویت دانشجویان و مشتریان
]

# CSRF trusted origins (for admin panel)
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:8000",
    "https://k.htni.ir",
    "https://app.ayareto.ir",
    "https://api.ayareto.ir",
    "https://api.ayareto.com",
    "https://app.ayareto.com",
    "https://htni.ir",
]

# Custom User Model
# Set this to use our custom User model instead of Django's default
AUTH_USER_MODEL = 'users_app.User'

# Custom Authentication Backend
# Use our custom backend for Django admin authentication
AUTHENTICATION_BACKENDS = [
    'users_app.backends.CustomUserBackend',
]

# Swagger/OpenAPI Settings
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'ClientToken': {
            'type': 'apiKey',
            'name': 'X-Client-Token',
            'in': 'header',
            'description': 'Client API token for customer authentication'
        }
    },
    'USE_SESSION_AUTH': False,
    'JSON_EDITOR': False,
    'SUPPORTED_SUBMIT_METHODS': [],  # Disable Try it out button - read-only mode
    'OPERATIONS_SORTER': 'alpha',
    'TAGS_SORTER': 'alpha',
    'DOC_EXPANSION': 'list',
    'DEEP_LINKING': True,
    'SHOW_EXTENSIONS': True,
    'DEFAULT_MODEL_RENDERING': 'example',
}

REDOC_SETTINGS = {
    'LAZY_RENDERING': True,
    'HIDE_HOSTNAME': False,
    'EXPAND_RESPONSES': '200,201',
    'PATH_IN_MIDDLE': True,
}
