# Generated by Django 6.0 on 2025-12-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'roadmap.ability',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=1)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('mo', models.BooleanField()),
                ('point', models.IntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True, db_column='createAt')),
                ('modified_at', models.DateTimeField(blank=True, db_column='modifiedAt', null=True)),
                ('expier_at', models.DateTimeField(blank=True, db_column='expierAt', null=True)),
                ('is_active', models.BooleanField(db_column='isActive', default=True)),
                ('at_least_point', models.IntegerField(blank=True, db_column='atLeastPoint', null=True)),
            ],
            options={
                'db_table': 'roadmap.mission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MissionRelation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'roadmap.missionRelation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MissionResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=50)),
                ('user_grant', models.IntegerField(blank=True, db_column='userGrant', null=True)),
                ('quiz_id', models.IntegerField(blank=True, db_column='quizId', null=True)),
            ],
            options={
                'db_table': 'roadmap.missionResult',
                'managed': False,
            },
        ),
    ]
