# Generated by Django 6.0 on 2025-12-29 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ability',
            table='ability',
        ),
        migrations.AlterModelTable(
            name='mission',
            table='mission',
        ),
        migrations.AlterModelTable(
            name='missionrelation',
            table='missionrelation',
        ),
        migrations.AlterModelTable(
            name='missionresult',
            table='missionresult',
        ),
    ]
