# Generated by Django 6.0 on 2026-01-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap_app', '0003_missiontype_and_mission_type_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('ctatext', models.CharField(blank=True, db_column='ctatext', max_length=255, null=True)),
            ],
            options={
                'db_table': 'missiontype',
                'managed': False,
            },
        ),
    ]
