# Generated by Django 6.0 on 2026-01-27 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap_app', '0004_missiontype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MissionType',
        ),
    ]
