# Generated by Django 6.0 on 2025-12-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.BooleanField()),
                ('accept_score', models.IntegerField(db_column='acceptScore')),
                ('number_of_question', models.IntegerField(db_column='numberOfQuestion')),
                ('create_at', models.DateTimeField(auto_now_add=True, db_column='createAt')),
                ('is_active', models.BooleanField(db_column='isActive', default=True)),
                ('can_back', models.BooleanField(db_column='canBack', default=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'exam.evaluation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('img', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.BooleanField()),
                ('c1', models.TextField(blank=True, null=True)),
                ('c2', models.TextField(blank=True, null=True)),
                ('c3', models.TextField(blank=True, null=True)),
                ('c4', models.TextField(blank=True, null=True)),
                ('correct', models.IntegerField(blank=True, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('can_shuffle', models.BooleanField(db_column='canShuffle', default=False)),
            ],
            options={
                'db_table': 'exam.question',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_at', models.DateTimeField(auto_now_add=True, db_column='startAt')),
                ('end_at', models.DateTimeField(blank=True, db_column='endAt', null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('is_accept', models.BooleanField(blank=True, db_column='isAccept', null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'exam.quiz',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuizResponse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.IntegerField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('done', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'exam.quizResponse',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuizResponseEvaluation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'exam.quizResponseEvaluation',
                'managed': False,
            },
        ),
    ]
