# Generated by Django 6.0 on 2025-12-27 11:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('product_id', models.IntegerField(blank=True, db_column='productId', null=True)),
                ('file_name', models.CharField(db_column='fileName', max_length=255)),
                ('file_type', models.CharField(db_column='fileType', max_length=50)),
                ('file_size', models.BigIntegerField(blank=True, db_column='fileSize', null=True)),
                ('path', models.TextField()),
                ('bucket', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(db_column='isPublic', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
            ],
            options={
                'db_table': 'media.file',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FileTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'media.fileTag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'media.tag',
                'managed': False,
            },
        ),
    ]
