# Generated by Django 6.0 on 2025-12-29 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='file',
            table='file',
        ),
        migrations.AlterModelTable(
            name='filetag',
            table='filetag',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='tag',
        ),
    ]
